apiVersion: v1
kind: PersistentVolume
metadata:
  name: recipe-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/c/recipe"
